/* 1000:61cb */

/* WARNING: Instruction at (ram,0x00016220) overlaps instruction at (ram,0x0001621d)
    */
/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Removing unreachable block (ram,0x00016220) */

uint FUN_1000_61cb(int param_1,undefined2 *param_2,uint *param_3,int param_4)

{
  byte *pbVar1;
  char *pcVar2;
  int *piVar3;
  uint *puVar4;
  undefined2 *puVar5;
  uint uVar6;
  undefined1 uVar7;
  byte extraout_AL;
  uint in_AX;
  undefined2 uVar8;
  byte bVar13;
  uint uVar9;
  uint uVar10;
  int iVar11;
  uint uVar12;
  char extraout_AH;
  uint in_CX;
  uint in_DX;
  uint extraout_DX;
  byte bVar14;
  uint in_BX;
  char cVar16;
  int iVar15;
  undefined2 *unaff_BP;
  undefined2 *unaff_SI;
  int iVar17;
  uint *puVar18;
  uint *puVar19;
  undefined2 *unaff_DI;
  uint *puVar20;
  byte *pbVar21;
  byte *pbVar22;
  int unaff_ES;
  undefined2 unaff_SS;
  int unaff_DS;
  byte in_CF;
  bool bVar23;
  char cVar24;
  bool bVar25;
  bool in_ZF;
  undefined1 in_SF;
  undefined4 uVar26;
  
  puVar20 = unaff_DI + 1;
  puVar18 = unaff_SI + 1;
  *unaff_DI = *unaff_SI;
  if ((bool)in_CF || in_ZF) {
    in_CX = 0x2002;
    bVar14 = FUN_1000_a120();
    *(byte *)0xe83a = *(byte *)0xe83a & (byte)in_CX;
    cVar24 = '\x14';
    puVar5 = (undefined2 *)register0x00000010;
    do {
      unaff_BP = unaff_BP + -1;
      puVar5 = puVar5 + -1;
      *puVar5 = *unaff_BP;
      cVar24 = cVar24 + -1;
    } while ('\0' < cVar24);
    pbVar1 = (byte *)((int)puVar20 + in_BX + 0x30);
    *pbVar1 = *pbVar1 ^ bVar14;
    uVar26 = FUN_1000_771b();
    in_DX = (uint)((ulong)uVar26 >> 0x10);
    in_AX = (int)uVar26 + 1;
LAB_1000_61a3:
    in_DX = CONCAT11((char)(in_DX >> 8) + ((byte *)((int)register0x00000010 + (int)puVar20))[0x3041]
                     ,(char)in_DX);
    *(byte *)((int)register0x00000010 + (int)puVar18) =
         *(byte *)((int)register0x00000010 + (int)puVar18) | (byte)in_AX;
LAB_1000_61a9:
    in_AX = CONCAT11((char)(in_AX >> 8),(byte)in_AX >> 7);
    iVar17 = in_BX + 1;
    *(byte *)((int)register0x00000010 + (int)puVar18) =
         *(byte *)((int)register0x00000010 + (int)puVar18) ^ (byte)in_DX;
    unaff_BP = (undefined2 *)((uint)register0x00000010 & (uint)puVar20);
    *(undefined2 *)0x3e76 = puVar20;
    unaff_BP[1] = iVar17;
    in_CF = false;
    bVar14 = (byte)iVar17 & *(byte *)((int)unaff_BP + (int)puVar18);
    in_BX = CONCAT11((char)((uint)iVar17 >> 8),bVar14);
    in_ZF = bVar14 == 0;
LAB_1000_61bb:
    puVar4 = puVar18;
    puVar18 = (uint *)((int)puVar18 + 1);
    out((byte)*puVar4,in_DX);
    if (!(bool)in_CF && !in_ZF) {
      if ((bool)in_CF || in_ZF) {
        *(byte *)(in_BX + (int)puVar18) = *(byte *)(in_BX + (int)puVar18) ^ (byte)in_DX;
        cVar24 = CARRY1((char)in_AX + (char)(in_AX >> 8) * -0x42,*(byte *)0x5056);
        goto code_r0x00016238;
      }
      puVar4 = puVar18;
      *(byte *)puVar4 = (byte)*puVar4 ^ (byte)in_CX;
      if ((POPCOUNT((byte)*puVar4) & 1U) == 0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
        halt_baddata();
      }
LAB_1000_623f:
      cVar24 = false;
      in_BX = in_BX & *(uint *)(in_BX + (int)puVar18);
      puVar18 = (uint *)0x3e50;
      goto code_r0x00016238;
    }
  }
  else {
    register0x00000010 = (BADSPACEBASE *)unaff_BP;
    if ((bool)in_CF || in_ZF) goto LAB_1000_61a3;
    if ((bool)in_CF || in_ZF) goto LAB_1000_61bb;
    if ((bool)in_CF || in_ZF) {
      bVar13 = (byte)(in_DX >> 8);
      bVar14 = bVar13 - *(byte *)(in_BX + 0x35);
      bVar23 = bVar13 < *(byte *)(in_BX + 0x35) || bVar14 < in_CF;
      cVar24 = bVar14 - in_CF;
      in_DX = CONCAT11(cVar24,(char)in_DX);
      in_SF = cVar24 < '\0';
      in_ZF = cVar24 == '\0';
code_r0x000161d8:
      if (!bVar23 && !in_ZF) goto LAB_1000_622e;
      while (bVar23 || in_ZF) {
        if (!bVar23 && !in_ZF) {
          func_0x0001636f();
          iVar17 = func_0x0001752d();
          *(int *)(in_BX - 0x76) = *(int *)(in_BX - 0x76) + iVar17 + 1;
          in_AX = FUN_1000_8b29();
          unaff_DS = param_1;
LAB_1000_617f:
          cVar24 = (char)in_AX;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
          *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar24;
                    /* WARNING: Bad instruction - Truncating control flow here */
          halt_baddata();
        }
        if (!bVar23 && !in_ZF) goto LAB_1000_617f;
        while( true ) {
          if (!bVar23 && !in_ZF) goto LAB_1000_61a9;
          if (!bVar23 && !in_ZF) break;
          if (!bVar23 && !in_ZF) goto LAB_1000_620d;
          if ((bool)in_SF) goto LAB_1000_6255;
          puVar4 = puVar18;
          puVar18 = puVar18 + 1;
          in_AX = *puVar4;
          in_CF = 0;
          if ((byte)in_AX == 0) {
            if ((char)in_CX == '\0') {
              in_CX = 3;
            }
            goto LAB_1000_620d;
          }
          puVar4 = puVar20;
          puVar20 = (uint *)((int)puVar20 + 1);
          *(byte *)puVar4 = (byte)in_AX;
LAB_1000_61f0:
          uVar10 = in_DX + *(uint *)0x860b;
          bVar23 = CARRY2(in_DX,*(uint *)0x860b) || CARRY2(uVar10,(uint)in_CF);
          in_DX = uVar10 + in_CF;
          in_SF = (int)in_DX < 0;
          in_ZF = in_DX == 0;
          in_CX = in_CX - 1;
          if (in_CX == 0 || in_ZF) {
            return in_AX & (uint)unaff_BP;
          }
        }
      }
      goto LAB_1000_623f;
    }
    if (!(bool)in_CF && !in_ZF) goto LAB_1000_61f0;
    bVar23 = (bool)in_CF;
    if ((bool)in_CF || in_ZF) goto code_r0x000161d8;
LAB_1000_620d:
    func_0x0001ad4a();
    in_CX = in_CX & 0xff;
    iVar17 = 0x32ba - in_CX;
    uVar8 = func_0x00015e90();
    in_BX = CONCAT11((char)((uint)param_2 >> 8),(char)param_2 - *(char *)((int)param_2 + iVar17));
    *(byte *)0xe805 = *(byte *)0xe805 & (byte)uVar8;
    pbVar1 = (byte *)(in_BX + iVar17 + 2);
    bVar14 = *pbVar1;
    bVar13 = (byte)((uint)uVar8 >> 8);
    *pbVar1 = *pbVar1 - bVar13;
    pcVar2 = (char *)(in_BX + param_4 + 0xa06);
    *pcVar2 = (*pcVar2 - (byte)uVar8) - (bVar14 < bVar13);
    uVar26 = func_0x00019312();
    in_DX = (uint)((ulong)uVar26 >> 0x10);
    in_AX = (uint)uVar26;
    param_1 = param_4;
    puVar20 = param_3;
    param_2 = unaff_BP;
  }
LAB_1000_622e:
  bVar14 = (byte)(in_CX >> 8);
  cVar24 = CARRY1(bVar14,(byte)in_DX) ||
           CARRY1(bVar14 + (byte)in_DX,CARRY1((byte)in_AX,*(byte *)(unaff_BP + 0x18)));
  in_CX = in_CX & 0xff;
  puVar18 = (uint *)0x612;
code_r0x00016238:
  bVar14 = (byte)in_CX;
  cVar16 = (char)(in_BX >> 8);
  uVar7 = FUN_1000_5b27();
  out(0x23,uVar7);
  *(char *)(unaff_BP + 0x1f28) = (*(char *)(unaff_BP + 0x1f28) - cVar16) - cVar24;
  puVar19 = puVar18 + 1;
  *puVar20 = *puVar18;
  puVar18 = puVar18 + 2;
  puVar20[0x28] = *puVar19;
  puVar20 = puVar20 + 0x50;
  *(byte *)puVar18 = (byte)*puVar18 ^ bVar14;
LAB_1000_6255:
  *(byte *)puVar20 = (byte)*puVar18;
  iVar17 = 0x10;
  puVar18 = (uint *)(param_1 + -2);
  pbVar22 = (byte *)((int)puVar20 + -0x4b1);
  do {
    pbVar21 = pbVar22;
    puVar19 = puVar18;
    puVar18 = puVar19 + 1;
    uVar10 = *puVar19;
    *(uint *)(pbVar21 + -0x50) = uVar10;
    *(uint *)(pbVar21 + 0x50) = uVar10;
    uVar9 = CONCAT11((char)uVar10,(char)(uVar10 >> 8));
    uVar6 = uVar9 * 2;
    bVar14 = ((uVar10 & 0x100) != 0) << 7;
    iVar15 = CONCAT11(bVar14,CARRY2(uVar9,uVar9));
    uVar10 = uVar9 | uVar6 | uVar9 >> 1;
    bVar13 = (byte)(uVar10 >> 8);
    iVar11 = CONCAT11((char)uVar10,bVar13);
    pbVar21[-1] = CARRY2(uVar9,uVar9);
    *(int *)pbVar21 = iVar11;
    pbVar21[1] = bVar14;
    iVar17 = iVar17 + -1;
    pbVar22 = pbVar21 + 0x50;
  } while (iVar17 != 0);
  *(byte *)puVar18 = (byte)*puVar18 ^ bVar13;
  pbVar1 = pbVar21 + 0x4f;
  *pbVar1 = *pbVar1 + bVar13;
  pbVar21[0x4f] = bVar13;
  pbVar22 = pbVar21 + 0x51;
  uVar12 = iVar11 + 1;
  bVar14 = (byte)uVar12;
  *(byte *)(puVar18 + uVar9) =
       (byte)puVar18[uVar9] + bVar14 + (((uint)((int)puVar20 + -0x4b1) & 1) != 0);
  uVar10 = (param_1 + -2) * 0x100;
  bVar23 = (uVar10 & 0x400) != 0;
  if ((uVar10 & 0x800) == 0) {
    *(byte *)(puVar19 + 0x1a4) = (byte)puVar19[0x1a4] + (char)(uVar12 >> 8);
    pbVar21[0x50] = (byte)*puVar18;
    puVar18 = puVar18 + !bVar23;
    pbVar22 = pbVar22 + uVar12 + (uint)bVar23 * -2;
    pbVar1 = (byte *)((int)puVar18 + iVar15 + 0x10);
    *pbVar1 = *pbVar1 | (byte)(uVar9 >> 1);
    *(byte *)(iVar15 + (int)puVar18) = *(byte *)(iVar15 + (int)puVar18) << 1;
    LOCK();
    pbVar1 = (byte *)((int)puVar18 + iVar15 + 0x30ac);
    *pbVar1 = *pbVar1 ^ bVar14;
    UNLOCK();
  }
  iVar11 = *(int *)0x32a8;
  FUN_1000_5aba(bVar14,(char)puVar18);
  pbVar22[uVar6 + 0xbad9] = pbVar22[uVar6 + 0xbad9] - (byte)iVar17;
  pbVar22[uVar6] = pbVar22[uVar6] + (char)((uint)iVar17 >> 8);
  piVar3 = (int *)(iVar15 + iVar11 + 0x10ff);
  *piVar3 = *piVar3 >> ((byte)iVar17 & 0x1f);
  iVar17 = iVar15;
  cVar24 = extraout_AH;
  do {
    for (; iVar17 != 0; iVar17 = iVar17 + -1) {
      pbVar1 = pbVar22;
      pbVar22 = pbVar22 + (uint)bVar23 * -2 + 1;
      *pbVar1 = extraout_AL;
    }
    bVar25 = CARRY2((uint)pbVar22,extraout_DX);
    pbVar22 = pbVar22 + extraout_DX;
    cVar24 = cVar24 + -1;
    iVar17 = iVar15;
  } while (cVar24 != '\0');
  return (byte)-bVar25 + 0x6108 + (uint)bVar25;
}


