/* 1000:61da */

/* WARNING: Instruction at (ram,0x00016220) overlaps instruction at (ram,0x0001621d)
    */
/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Removing unreachable block (ram,0x00016220) */
/* WARNING: Removing unreachable block (ram,0x00016230) */

uint FUN_1000_61da(int param_1,uint param_2,byte *param_3,int param_4)

{
  char *pcVar1;
  int *piVar2;
  uint *puVar3;
  byte *pbVar4;
  uint uVar5;
  byte bVar6;
  undefined1 uVar7;
  byte extraout_AL;
  uint in_AX;
  undefined2 uVar8;
  uint uVar9;
  uint uVar10;
  int iVar11;
  uint uVar12;
  char extraout_AH;
  uint in_CX;
  byte bVar13;
  uint in_DX;
  uint extraout_DX;
  uint extraout_DX_00;
  byte bVar14;
  int in_BX;
  int iVar15;
  uint unaff_BP;
  uint *unaff_SI;
  int iVar16;
  undefined2 *puVar17;
  uint *puVar18;
  uint *puVar19;
  byte *unaff_DI;
  byte *pbVar20;
  byte *pbVar21;
  int unaff_ES;
  undefined2 unaff_SS;
  int unaff_DS;
  undefined1 in_CF;
  char cVar22;
  bool bVar23;
  undefined1 in_ZF;
  undefined1 in_SF;
  bool bVar24;
  
code_r0x000161da:
  cVar22 = (char)in_AX;
  if (!(bool)in_CF && !(bool)in_ZF) {
LAB_1000_623f:
    bVar6 = (byte)in_CX;
    cVar22 = false;
    bVar14 = (byte)((uint)in_BX >> 8) &
             (byte)((uint)*(undefined2 *)(byte *)(in_BX + (int)unaff_SI) >> 8);
    puVar17 = (undefined2 *)0x3e50;
code_r0x00016238:
    uVar7 = FUN_1000_5b27();
    out(0x23,uVar7);
    *(char *)(unaff_BP + 0x3e50) = (*(char *)(unaff_BP + 0x3e50) - bVar14) - cVar22;
    *(undefined2 *)unaff_DI = *puVar17;
    unaff_SI = puVar17 + 2;
    *(undefined2 *)(unaff_DI + 0x50) = puVar17[1];
    unaff_DI = unaff_DI + 0xa0;
    *(byte *)unaff_SI = (byte)*unaff_SI ^ bVar6;
LAB_1000_6255:
    *unaff_DI = (byte)*unaff_SI;
    iVar16 = 0x10;
    puVar19 = (uint *)(param_1 + -2);
    pbVar21 = unaff_DI + -0x4b1;
    do {
      pbVar20 = pbVar21;
      puVar18 = puVar19;
      puVar19 = puVar18 + 1;
      uVar10 = *puVar18;
      *(uint *)(pbVar20 + -0x50) = uVar10;
      *(uint *)(pbVar20 + 0x50) = uVar10;
      uVar9 = CONCAT11((char)uVar10,(char)(uVar10 >> 8));
      uVar5 = uVar9 * 2;
      bVar6 = ((uVar10 & 0x100) != 0) << 7;
      iVar15 = CONCAT11(bVar6,CARRY2(uVar9,uVar9));
      uVar10 = uVar9 | uVar5 | uVar9 >> 1;
      bVar14 = (byte)(uVar10 >> 8);
      iVar11 = CONCAT11((char)uVar10,bVar14);
      pbVar20[-1] = CARRY2(uVar9,uVar9);
      *(int *)pbVar20 = iVar11;
      pbVar20[1] = bVar6;
      iVar16 = iVar16 + -1;
      pbVar21 = pbVar20 + 0x50;
    } while (iVar16 != 0);
    *(byte *)puVar19 = (byte)*puVar19 ^ bVar14;
    pbVar4 = pbVar20 + 0x4f;
    *pbVar4 = *pbVar4 + bVar14;
    pbVar20[0x4f] = bVar14;
    pbVar21 = pbVar20 + 0x51;
    uVar12 = iVar11 + 1;
    bVar6 = (byte)uVar12;
    *(byte *)(puVar19 + uVar9) =
         (byte)puVar19[uVar9] + bVar6 + (((uint)(unaff_DI + -0x4b1) & 1) != 0);
    uVar10 = (param_1 + -2) * 0x100;
    bVar24 = (uVar10 & 0x400) != 0;
    if ((uVar10 & 0x800) == 0) {
      *(byte *)(puVar18 + 0x1a4) = (byte)puVar18[0x1a4] + (char)(uVar12 >> 8);
      pbVar20[0x50] = (byte)*puVar19;
      puVar19 = puVar19 + !bVar24;
      pbVar21 = pbVar21 + uVar12 + (uint)bVar24 * -2;
      pbVar4 = (byte *)((int)puVar19 + iVar15 + 0x10);
      *pbVar4 = *pbVar4 | (byte)(uVar9 >> 1);
      *(byte *)(iVar15 + (int)puVar19) = *(byte *)(iVar15 + (int)puVar19) << 1;
      LOCK();
      pbVar4 = (byte *)((int)puVar19 + iVar15 + 0x30ac);
      *pbVar4 = *pbVar4 ^ bVar6;
      UNLOCK();
    }
    iVar11 = *(int *)0x32a8;
    FUN_1000_5aba(bVar6,(char)puVar19);
    pbVar21[uVar5 + 0xbad9] = pbVar21[uVar5 + 0xbad9] - (byte)iVar16;
    pbVar21[uVar5] = pbVar21[uVar5] + (char)((uint)iVar16 >> 8);
    piVar2 = (int *)(iVar15 + iVar11 + 0x10ff);
    *piVar2 = *piVar2 >> ((byte)iVar16 & 0x1f);
    iVar16 = iVar15;
    cVar22 = extraout_AH;
    do {
      for (; iVar16 != 0; iVar16 = iVar16 + -1) {
        pbVar4 = pbVar21;
        pbVar21 = pbVar21 + (uint)bVar24 * -2 + 1;
        *pbVar4 = extraout_AL;
      }
      bVar23 = CARRY2((uint)pbVar21,extraout_DX_00);
      pbVar21 = pbVar21 + extraout_DX_00;
      cVar22 = cVar22 + -1;
      iVar16 = iVar15;
    } while (cVar22 != '\0');
    return (byte)-bVar23 + 0x6108 + (uint)bVar23;
  }
  if ((bool)in_CF || (bool)in_ZF) {
    if ((bool)in_CF || (bool)in_ZF) {
      do {
        if (!(bool)in_CF && !(bool)in_ZF) {
          bVar6 = (byte)(in_AX >> 7) & 1;
          iVar16 = in_BX + 1;
          *(byte *)(unaff_BP + (int)unaff_SI) = *(byte *)(unaff_BP + (int)unaff_SI) ^ (byte)in_DX;
          unaff_BP = unaff_BP & (uint)unaff_DI;
          *(undefined2 *)0x3e76 = unaff_DI;
          *(int *)(unaff_BP + 2) = iVar16;
          bVar14 = (byte)iVar16 & *(byte *)(unaff_BP + (int)unaff_SI);
          in_BX = CONCAT11((char)((uint)iVar16 >> 8),bVar14);
          puVar3 = unaff_SI;
          unaff_SI = (uint *)((int)unaff_SI + 1);
          out((byte)*puVar3,in_DX);
          if (bVar14 != 0) {
            puVar3 = unaff_SI;
            *(byte *)puVar3 = (byte)*puVar3 ^ (byte)in_CX;
            if ((POPCOUNT((byte)*puVar3) & 1U) == 0) {
                    /* WARNING: Bad instruction - Truncating control flow here */
              halt_baddata();
            }
            goto LAB_1000_623f;
          }
LAB_1000_622e:
          bVar14 = (byte)((uint)in_BX >> 8);
          bVar13 = (byte)(in_CX >> 8);
          cVar22 = CARRY1(bVar13,(byte)in_DX) ||
                   CARRY1(bVar13 + (byte)in_DX,CARRY1(bVar6,*(byte *)(unaff_BP + 0x30)));
          bVar6 = (byte)in_CX;
          puVar17 = (undefined2 *)0x612;
          goto code_r0x00016238;
        }
        if (!(bool)in_CF && !(bool)in_ZF) goto code_r0x000161da;
        if (!(bool)in_CF && !(bool)in_ZF) {
LAB_1000_620d:
          func_0x0001ad4a();
          in_CX = in_CX & 0xff;
          iVar16 = 0x32ba - in_CX;
          uVar8 = func_0x00015e90();
          in_BX = CONCAT11((char)(param_2 >> 8),(char)param_2 - *(char *)(param_2 + iVar16));
          *(byte *)0xe805 = *(byte *)0xe805 & (byte)uVar8;
          pbVar4 = (byte *)(in_BX + iVar16 + 2);
          bVar6 = *pbVar4;
          bVar14 = (byte)((uint)uVar8 >> 8);
          *pbVar4 = *pbVar4 - bVar14;
          pcVar1 = (char *)(in_BX + param_4 + 0xa06);
          *pcVar1 = (*pcVar1 - (byte)uVar8) - (bVar6 < bVar14);
          bVar6 = func_0x00019312();
          param_1 = param_4;
          in_DX = extraout_DX;
          unaff_DI = param_3;
          param_2 = unaff_BP;
          goto LAB_1000_622e;
        }
        if ((bool)in_SF) goto LAB_1000_6255;
        puVar3 = unaff_SI;
        unaff_SI = unaff_SI + 1;
        in_AX = *puVar3;
        if ((byte)in_AX == 0) {
          if ((byte)in_CX == 0) {
            in_CX = 3;
          }
          goto LAB_1000_620d;
        }
        pbVar4 = unaff_DI;
        unaff_DI = unaff_DI + 1;
        *pbVar4 = (byte)in_AX;
        in_CF = CARRY2(in_DX,*(uint *)0x860b);
        in_DX = in_DX + *(uint *)0x860b;
        in_SF = (int)in_DX < 0;
        in_ZF = in_DX == 0;
        in_CX = in_CX - 1;
        if (in_CX == 0 || (bool)in_ZF) {
          return in_AX & unaff_BP;
        }
      } while( true );
    }
  }
  else {
    func_0x0001636f();
    iVar16 = func_0x0001752d();
    *(int *)(in_BX + -0x76) = *(int *)(in_BX + -0x76) + iVar16 + 1;
    cVar22 = FUN_1000_8b29();
    unaff_DS = param_1;
  }
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
  *(char *)(in_BX + unaff_ES) = *(char *)(in_BX + unaff_ES) + cVar22;
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


